version: '3'

services:
#MongoDB services
  mongo_db:
    container_name: db_yumseek_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db

#Node js User api services
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: yumseek
      TOKEN_SECRET: blah1478
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}